### PR TITLE
Do not directly use isolated surrogates in unicode literals

### PR DESCRIPTION
**Pull request by jimbaker**
Jython does not support isolated surrogates in unicode, including in unicode literals. This has been reported in https://github.com/html5lib/html5lib-python/issues/2 This bug is critical for Jython due to the fact that html5lib is a vendor lib for pip, and this is blocking pip from running on Jython.

For platforms besides Jython, this pull request allows for these surrogates to be constructed in literals, but through an additional step of indirection. For Jython itself, Jython's normal decode of literals will ensure that such invalid unicode strings cannot be constructed from any source.

To run this on Jython:

1. Install https://bitbucket.org/jimbaker/jython-socket-reboot, following these instructions: https://wiki.python.org/jython/JythonDeveloperGuide

2. Use this branch of pip to install nosetests, etc.: https://github.com/jimbaker/pip Note that tox is not yet supported - because we need to get pip running first! :)

Note that in the dev build, you will find executables in dist/bin, such as dist/bin/jython or dist/bin/pip

The jython-socket-reboot branch is nearly complete for merging into Jython; it is a major component of Jython 2.7.0 beta 3. (I'm a core dev of Jython.)

### CODE REVIEW

**Comment by tseaver** [comment]
I was hoping that the recent [jython 2.7b4 release](http://fwierzbicki.blogspot.com/2015/02/jython-27-beta4-released.html) somehow worked around this problem, but it is still borken.

**Comment by tseaver** [comment]
Hmm, I don't know of any resolution here.  Are you in the process of merging #168?

**Comment by gsnedders** [comment]
Just closing this because #168 is it's replacement rather than keeping both open.

**Comment by gsnedders** [comment]
(We'll see if anything happens soon. Maybe.)

**Pull request closed without merging**
