### PR TITLE
make compatible with python 3.6

### PR DESCRIPTION
**Pull request by moben**
errors on invalid escape sequences in strings, such as "\s"

i.e. anything not mentioned in https://docs.python.org/3/reference/lexical_analysis.html#strings

### CODE REVIEW

**Comment by gsnedders** [comment]
Oh, this isn't compatibility per-se, this is just avoiding DeprecationWarnings? (So it's essentially compatibility with some future version.)

**Comment by moben** [comment]
yes. Looking again I might have run into it with `-Werror` I guess.

Still a good idea, though for a future python version.

**Comment by gsnedders** [comment]
Oh, totally, still a good idea; thanks for the patch!

**Comment by gsnedders** [comment]
(In case it was unclear: I didn't merge it earlier because I was still waiting on Travis CI to finish running against the merge with the Travis fix.)

**Pull request merged**
