### PR TITLE
Remove Travis CI in favour of GitHub Actions

### PR DESCRIPTION
**Pull request by hugovk**
Fixes https://github.com/html5lib/html5lib-python/issues/525.

GitHub Actions was added in https://github.com/html5lib/html5lib-python/pull/527, and tests are also run on AppVeyor for Windows (this could also be moved to GHA, but that's another issue).

Also Travis CI hasn't been running for 10 months:

image

https://travis-ci.org/github/html5lib/html5lib-python/builds

### CODE REVIEW

**Review by jayaddison — APPROVED** [review]
(disclaimer: minimal-contributor review) this looks good to me; checked the hyperlinks and badge images :+1:

**Comment by hugovk** [comment]
Thanks! And I've fixed the nonsensical PR title 🙃 

I can fix the commit message too if you like :)

**Comment by jayaddison** [comment]
Hehe, oops - I didn't spot those :)  Yep, sounds good!

**Comment by hugovk** [comment]
Fixed! :D

**Pull request merged**
