### PR TITLE
Fix spider

### PR DESCRIPTION
**Pull request by jayvdb**
This change is [Reviewable](https://reviewable.io/reviews/html5lib/html5lib-python/294)

### CODE REVIEW

**Comment by jayvdb** [comment]
We could probably replace most of this with an existing library.

**Comment by Ms2ger** [comment]
Can we use `six` for the `urllib` imports?

**Comment by jayvdb** [comment]
Using `six` here looks good; I checked and it provides `robotparser`, since 2013 (https://bitbucket.org/gutworth/six/pull-requests/5/create-sixmovesurllib/diff / https://bitbucket.org/gutworth/six/commits/1f2c7f5d14be9027d180aa00138a1d29c8f48a6f).
Should I find a minimum version for six support?  Currently it doesnt have one.

**Comment by gsnedders** [comment]
As far as I'm aware, nobody's actually run it for years hence it being badly broken. We should probably just kill it at this point, as it likely has no real use.

**Comment by willkg** [comment]
Given the previous comment, I'm going to close this out. I opened #349 to cover removing `utils/spider.py`.

**Pull request closed without merging**
