### PR TITLE
Add AppVeyor testing

### PR DESCRIPTION
**Pull request by jayvdb**
This is the first subset of https://github.com/html5lib/html5lib-python/pull/293 .

### CODE REVIEW

**Comment by jayvdb** [comment]
Example build https://ci.appveyor.com/project/jayvdb17618/html5lib-python/build/1.0.26

**Comment by willkg** [comment]
After we land this, we need to set up appveyor as a CI thing, right? Is there anything else we need to do?

**Comment by jayvdb** [comment]
Not mandatory; devs can just do it on their forks if you're not keen on it being part of the PR process.

I've chosen to use `.appveyor.yml` instead of the default `appveyor.yml` , which means that there is one additional setup step : specifying the file in the AppVeyor settings.
I'm having to use the default filename if you'd prefer.

**Comment by gsnedders** [comment]
@willkg lmk if I need to do anything to enable AppVeyor on the repo!

**Comment by willkg** [comment]
@jayvdb Naming the file that is fine by me. I want this to be part of the PR process. I'll figure out whether I can add it on my own and if not, ping @gsnedders for help.

Thank you!

**Comment by gsnedders** [comment]
Now added.

**Comment by willkg** [comment]
@gsnedders Thank you!

**Pull request merged**
