### PR TITLE
Remove support for end-of-life Python 2.7

### PR DESCRIPTION
**Pull request by jdufresne**
Python 2.7 has been EOL since 2020-01-01. It is no longer receiving
security updates.

By removing Python 2 support, can reduce testing resources and simplify
the code by removing compatibility shims.

Removes dependency on six.

Removes test dependency on mock.

### CODE REVIEW

**Comment by jgraham** [comment]
I am strongly opposed to this. There are still many consumers of html5lib who can't or haven't migrated to Python 3. Although PSF is no longer supporting Python 2.7 it's still under support in e.g. RHEL.

**Comment by jdufresne** [comment]
No problem. With this change, I'm only trying to help this project and the larger Python community. I figure sooner or later, someone would need to do this maintenance work. If the project policy is to continue supporting Python 2.7, no worries.

That said, Python 2.7 user can continue using the last release of html5lib that supported 2.7 which is 1.0.1 as of this writing, released Dec 7, 2017. As users haven't had a new release in over a year, there wouldn't really be any immediate change for them. The setup.py file users `python_requires` so pip would choose the best compatible version automatically.

**Comment by gsnedders** [comment]
Note that this implies pip staying on the last Py2-supporting release, which is potentially troublesome given the current last Py2 release doesn't support Py3.future and implies pip vending multiple versions of html5lib. I'd rather stick to the somewhat unwritten policy of supporting at least the same versions that pip supports (and we should document that).

Let's move any discussion about the policy to #439, and close this for now.

**Comment by jdufresne** [comment]
Now that [pip has dropped support for Python 2](https://github.com/pypa/pip/commit/be9637f7f57d1d6e97dfbdd2bdc698edbba73d9f), perhaps this PR can be reconsidered? If so, I'll happily rebase.

**Pull request closed without merging**
