### PR TITLE
Add a more general fix for #127 (CPy #20007) based on #136.

### PR DESCRIPTION
**Pull request by gsnedders**
This gets stuff working with `urllib.response.addurlinfo`. See #127 and #136.

### CODE REVIEW

**Comment by gsnedders** [comment]
@SimonSapin this may be of interest to you (maybe)

**Comment by SimonSapin** [comment]
According to https://github.com/Kozea/WeasyPrint/commit/e14653c10260a7edd3b7416d6438b63939865336 , html5lib 0.999 already had a work around that was enough for WeasyPrint. Probably https://github.com/html5lib/html5lib-python/commit/18bc2787aa1156bd826eed62e54ec6bbb8403d76.

**Comment by SimonSapin** [comment]
Oh, looking closer, this is a similar but different work around. I don’t remember WeasyPrint being affected by that one, though.

**Comment by gsnedders** [comment]
Yeah, from memory you for were just trying to get it to be more complete, rather than needing it yourself. I think?

**Comment by SimonSapin** [comment]
Maybe. But to be honest I’ve kind of moved on from Python :)

**Pull request merged**
