### PR TITLE
Scripting disabled case

### LINKED ISSUE #10: Implement scripting disabled case.
Since people have requested this.

### PR DESCRIPTION
**Pull request by gsnedders**
This essentially rebases #230 as well as squashing it, and fixes tree walker tests to set the scripting flag correctly. Still fixes #10. //cc @neumond

### CODE REVIEW

**Comment by gsnedders** [comment]
So we don't have tests for "in head noscript" insertion mode, that kinda sucks.

**Comment by gsnedders** [comment]
Also:

```
(py2-env)pnin:html5lib-python gsnedders$ python parse.py foo.html 
Traceback (most recent call last):
  File "parse.py", line 97, in run
    document = parseMethod(f, encoding=encoding)
  File "/Users/gsnedders/Documents/my-projects/html5lib/html5lib-python/html5lib/html5parser.py", line 239, in parse
    parseMeta=parseMeta, useChardet=useChardet, scripting=scripting)
  File "/Users/gsnedders/Documents/my-projects/html5lib/html5lib-python/html5lib/html5parser.py", line 94, in _parse
    self.mainLoop()
  File "/Users/gsnedders/Documents/my-projects/html5lib/html5lib-python/html5lib/html5parser.py", line 217, in mainLoop
    reprocess = self.phase.processEOF()
  File "/Users/gsnedders/Documents/my-projects/html5lib/html5lib-python/html5lib/html5parser.py", line 469, in processEOF
    raise NotImplementedError
NotImplementedError
(py2-env)pnin:html5lib-python gsnedders$ cat foo.html 
<head><noscript></head>
```

**Comment by neumond** [comment]
Looks good to me.

**Comment by gsnedders** [comment]
https://github.com/html5lib/html5lib-tests/pull/76 deals with the testing side of things.

**Pull request merged**
