### PR TITLE
Fix arguments order in error message

### PR DESCRIPTION
**Pull request by sigmundch**

### CODE REVIEW

**Comment by gsnedders** [comment]
@sigmundch  Given dicts have no order, how is there any issue here?

**Comment by sigmundch** [comment]
Note that this swaps which key is associated with each value (e.g. `expectedName` should be `node.name` rather than `body`). So if you have:

```html
<div></span>
``` 

The error used to say:
`Unexpected end tag (div). Missing end tag (span).`

Now the error will say:
`Unexpected end tag (span). Missing end tag (div).`

**Comment by gsnedders** [comment]
Oh. I can't read. Duh. :)

**Comment by gsnedders** [comment]
rebased & landed as 3ebdd8bc2e4b751218e5189f8ff40e45d926efb2

**Pull request closed without merging**
