### PR TITLE
Remove last note about nose

### PR DESCRIPTION
**Pull request by willkg**
This nixes the last bit about nose re: issue #182.

### CODE REVIEW

**Comment by willkg** [comment]
This is very cosmetic. Given the content and location of the file, part of me thinks we should remove it altogether.

@gsnedders @jgraham Can one of you review this, please?

**Comment by gsnedders** [comment]
I'd also be totally happy with removing it, honestly.

**Comment by willkg** [comment]
I'll change this PR to remove that file. Thank you!

**Comment by willkg** [comment]
@gsnedders I rebased on master tip to pick up the pytest fixes so that CI would pass. That caused the previous reviews to become stale, so this needs another review. Sorry about that!

**Comment by willkg** [comment]
Thank you!

**Pull request merged**
