### PR TITLE
Drop support for EOL Python 2.7, 3.5 and 3.6

### PR DESCRIPTION
**Pull request by hugovk**
Fixes https://github.com/html5lib/html5lib-python/issues/541.

The readme says:

> The goal is to support a (non-strict) superset of the versions that [pip supports](https://pip.pypa.io/en/stable/installing/#python-and-os-compatibility).

https://github.com/html5lib/html5lib-python#installation

pip supports:

> ~CPython 3.6, 3.7, 3.8, 3.9 and latest PyPy3.~

> CPython 3.7, 3.8, 3.9, 3.10 and latest PyPy3.

https://pip.pypa.io/en/stable/installation/#compatibility

Therefore this PR drops support for EOL 2.7, 3.5 and 3.6 and upgrades to modern syntax using pyupgrade. There will be more cleanup possible, but I didn't want this PR to get too big.

Similarly, if you'd prefer a smaller PR, like dropping support and removing six, but keeping the older syntax for another PR, just let me know!

### CODE REVIEW

**Comment by kloczek** [comment]
Looks like this PR should be rediffed against current master.

**Comment by hugovk** [comment]
Updated against master!

**Comment by hugovk** [comment]
Updated to fix this pytest deprecation warning: https://github.com/html5lib/html5lib-python/issues/529#issuecomment-1103988133.

**Comment by hugovk** [comment]
Since this was opened 11 months ago, Python 3.6 has gone EOL and been dropped by pip, so dropping here too.

**Review by kloczek — COMMENTED** [review]
Is possible to make new release?

**Comment by hugovk** [comment]
Closing this year old PR, happy to re-open if any interest 👍

**Pull request closed without merging**
