### PR TITLE
Add testing for Python 3.6 and document support

### PR DESCRIPTION
**Pull request by jdufresne**

### CODE REVIEW

**Comment by jdufresne** [comment]
Updated PR to resolve test failures after a recent rebase by removing

```bash
pip install pip==6.1.0
```

from `requirements-install.sh`

**Comment by gsnedders** [comment]
What's the default `pip` on Travis nowadays? It used to be 6.0.something, which didn't work for us. (See #319.)

**Comment by jdufresne** [comment]
AFAICT, It is not very well documented. This is what I found through experimentation:

Python 2.6.9
pip 9.0.1
setuptools 28.8.0

Python 2.7.13
pip 9.0.1
setuptools 36.3.0

Python 3.3.6
pip 8.1.2
setuptools 18.0.1

Python 3.4.6
pip 9.0.1
setuptools 35.0.2

Python 3.5.3
pip 9.0.1
setuptools 36.3.0

Python 3.6.3
pip 9.0.1
setuptools 36.5.0

Python 2.7.13 (c925e7381036, Jun 05 2017, 21:20:51)
[PyPy 5.8.0 with GCC 6.2.0 20160901]
pip 9.0.1
setuptools 36.2.3

Python 3.5.3 (a39af0be3a22, Jun 05 2017, 20:18:00)
[PyPy 5.8.0-beta0 with GCC 6.2.0 20160901]
pip 9.0.1
setuptools 36.2.3

**Comment by gsnedders** [comment]
Thanks!

**Pull request merged**
