### PR TITLE
Update tests/testdata (for <svg><p> in innerHTML)

### PR DESCRIPTION
**Pull request by zcorpan**
I didn't manage to get `py.test` working, so don't know if/how test expectations (in `.pytest.expect`) need changing.

cc @jgraham @gsnedders @annevk

### CODE REVIEW

**Comment by zcorpan** [comment]
I got `py.test` working now. I needed todo `pip install pytest-expect`...

**Comment by zcorpan** [comment]
OK, `py.test` passes now.

**Comment by annevk** [comment]
This seems fine, but I have no power here.

**Comment by zcorpan** [comment]
@jgraham ping

**Review by jgraham — APPROVED** [review]

**Pull request merged**
