### PR TITLE
Update html5parser.py

### PR DESCRIPTION
**Pull request by ta5ae**
Adding an initial definition of the new_phase variable as recently an application I work on managed to generate this error: a local variable 'new_phase' referenced before assignment.

### CODE REVIEW

**Comment by gsnedders** [comment]
Can you provide anything to reproduce the error? Almost certainly what you've written will merely delay an exception being thrown, it won't stop any exception from being thrown. To get such an exception there would imply the stack is empty, which would be very odd!

**Comment by ta5ae** [comment]
Sorry for the late reply, I presumed the calling code had caused the error.  Here is a snapshot of the error log:

Local Vars

Variable | Value
-------- | -----
container | u'div'
stream | u'I keep others at a distance'
useChardet | True
encoding | None
self | &lt;html5lib.html5parser.HTMLParser object at 0x7fee33ec4810&gt;
innerHTML | True
parseMeta | True
kwargs | {}
...lib/python2.7/site-packages/html5lib/html5parser.py in reset
            self.resetInsertionMode()

**Comment by gsnedders** [comment]
You wouldn't happen to have a stack trace? I'm pretty sure it should be impossible to have an empty stack, which is the only thing that should cause it.

**Comment by ta5ae** [comment]
I hesitate to send a full stack trace due to the need to clean up a lot of private client / company data.

However, I believe the issue lies with us using your library in a threaded environment.  We no longer do.  This would account with the odd results.  Sorry for reporting the red herring.

**Comment by gsnedders** [comment]
Ah, yes, that's plausible. We should better document that we're known to not be safe in a threaded environment. We should also fix it so we are safe.

Closing for now; if you happen to find evidence that it *isn't* down to threading, feel free to file a new issue and link to this.

**Pull request closed without merging**
